author_id = "olle"
app_id = "blutti"
author_name = "Olle Wreede"
app_name = "Blutti"

[files]
_splash = { path = "assets/blutti-title.png" }
spritesheet = { path = "assets/spritesheet.png" }
font = { path = "assets/eg_4x6.fff" }
level1 = { path = "assets/level1.json", copy = true }
level2 = { path = "assets/level2.json", copy = true }
level3 = { path = "assets/level3.json", copy = true }
level4 = { path = "assets/level4.json", copy = true }
level5 = { path = "assets/level5.json", copy = true }
sound_coin = { path = "assets/coin5.wav" }
sound_jump = { path = "assets/jump3.wav" }
sound_dash = { path = "assets/jump4.wav" }
sound_powerup = { path = "assets/powerup3.wav" }
sound_death = { path = "assets/death.wav" }
sound_exit = { path = "assets/round_end.wav" }
sound_wrong = { path = "assets/wrong3.wav" }
sound_theme = { path = "assets/hallowquest.wav" }

[badges]
1 = { name = "stars", steps = 100, descr = "Collect 100 stars" }
2 = { name = "levels", steps = 5, descr = "Finish 5 levels" }
3 = { name = "deaths", steps = 10, descr = "Die 10 times" }

[cheats]
set-level = 1
add-lives = 2
add-points = 3
die = 4
iddqd = 5
